name: flutterfairy
description: Personal blog

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.18.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  ##firebase
  firebase_core: ^2.2.0
  cloud_firestore: ^4.0.5
  firebase_analytics: ^10.0.5
  firebase_remote_config: ^3.0.4
  firebase_crashlytics: ^3.0.5

  ##services
  share_plus: ^4.0.10
  url_launcher: ^6.1.4
  device_info_plus: ^4.0.0
  network_info_plus: ^2.1.3
  package_info_plus: ^1.4.2
  geocoding: ^2.0.4

  ## state management control
  provider: ^6.0.2
  either_dart: ^0.1.4
  equatable: ^2.0.3
  get_it: ^7.2.0

  ## utils
  link_preview_generator: ^1.2.0
  open_mail_app: ^0.4.5
  intl: ^0.17.0
  extended_image: ^6.2.1
  shared_preferences: ^2.0.15
  qr_flutter: ^4.0.0
  random_string: ^2.3.1
  fluttertoast: ^8.0.9
  linkify: ^4.1.0
  social_share: ^2.2.1

  #UI
  modal_bottom_sheet: ^2.0.1
  flutter_datetime_picker: ^1.5.1
  visibility_detector: ^0.2.2
  shimmer: ^2.0.0
  responsive_builder: ^0.4.2
  flutter_markdown: ^0.6.13
  # new
  clipboard: ^0.1.3
  styled_text: ^5.1.0
  flutter_multi_formatter: ^2.5.1
  syntax_highlighter:
    git:
      url: https://github.com/josedoes/syntax_highlighter.git
  confetti: ^0.7.0
  code_editor: ^1.3.1
  flutter_highlight: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mocktail: ^0.3.0
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/
    - assets/icons/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
    - family: Courier New
      fonts:
        - asset: assets/fonts/Courier-New.ttf
