name: dashlingo
description: Learn dart & flutter

publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=2.18.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  ##firebase
  firebase_core: ^2.22.0
  firebase_auth: ^4.13.0
  cloud_firestore: ^4.13.0
  firebase_analytics: ^10.6.4
  google_sign_in: ^6.1.6

  ## state management control
  flutter_riverpod: ^2.4.5

  ## navigation
  go_router: ^12.1.1

  ## utils
  intl: ^0.18.1
  extended_image: ^8.1.1
  shared_preferences: ^2.2.2
  random_string: ^2.3.1
  linkify: ^5.0.0

  #UI
  modal_bottom_sheet: ^2.1.2
  visibility_detector: ^0.4.0+2
  shimmer: ^3.0.0

  styled_text: ^8.1.0
  flutter_multi_formatter: ^2.11.16
  # syntax_highlighter: ^0.1.1
  confetti: ^0.7.0
  code_editor: ^2.1.0
  flutter_highlight: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  network_image_mock: ^2.1.1
  flutter_lints: ^2.0.0
  mocktail: ^1.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/
    - assets/icons/

  fonts:
    - family: DINRoundPro
      fonts:
        - asset: assets/fonts/DINRoundPro-Regular.ttf
          weight: 400
        - asset: assets/fonts/DINRoundPro-Medium.ttf
          weight: 500
        - asset: assets/fonts/DINRoundPro-Bold.ttf
          weight: 700
    - family: Courier New
      fonts:
        - asset: assets/fonts/Courier-New.ttf
