name: dashlingo
description: Learn dart & flutter

publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=2.18.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  ##firebase
  firebase_core: ^2.7.0
  firebase_auth: ^4.2.9
  cloud_firestore: ^4.4.3
  firebase_analytics: ^10.1.4
  google_sign_in: ^6.0.2

  ## state management control
  provider: ^6.0.2
  either_dart: ^0.1.4
  equatable: ^2.0.3
  get_it: ^7.2.0

  ## utils
  intl: ^0.17.0
  extended_image: ^6.2.1
  shared_preferences: ^2.0.15
  random_string: ^2.3.1
  linkify: ^4.1.0

  #UI
  modal_bottom_sheet: ^2.0.1
  visibility_detector: ^0.2.2
  shimmer: ^2.0.0
  responsive_builder: ^0.4.2

  # new
  clipboard: ^0.1.3
  styled_text: ^5.1.0
  flutter_multi_formatter: ^2.5.1
  syntax_highlighter: ^0.1.1
  confetti: ^0.7.0
  code_editor: ^1.3.1
  flutter_highlight: ^0.7.0
  go_router: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mocktail: ^0.3.0
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/
    - assets/icons/

  fonts:
    - family: DINRoundPro
      fonts:
        - asset: assets/fonts/DINRoundPro-Regular.ttf
          weight: 400
        - asset: assets/fonts/DINRoundPro-Medium.ttf
          weight: 500
        - asset: assets/fonts/DINRoundPro-Bold.ttf
          weight: 700
    - family: Courier New
      fonts:
        - asset: assets/fonts/Courier-New.ttf
